import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-reinsurance-collateral-trust-funding-reconciliation",
  "engine": "recovery",
  "title": "Reinsurance Collateral & Trust Funding Reconciliation",
  "shortTitle": "Reinsurance Collateral and Trust Funding Reconciliation",
  "tagline": "Calculate required collateral and prevent excess funding, shortfalls, and delayed trust or letter-of-credit releases.",
  "industry": "Reinsurance Finance",
  "buyer": "Cedents, reinsurers, and captive managers",
  "uiPort": 4662,
  "apiPort": 5662,
  "accent": "#0f766e",
  "currency": "USD",
  "primaryOutcome": "Reinsurance Collateral & Trust Funding Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect reinsurance agreements, reserves, paid losses, recoverables, letters of credit, trust assets, haircuts, ratings, collateral calls, and releases in one accountable workflow. Calculate required collateral and prevent excess funding, shortfalls, and delayed trust or letter-of-credit releases.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Reinsurance Collateral & Trust Funding Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("agreement-collateral-terms","RCT01","Agreement collateral terms","Execute agreement collateral terms using reinsurance agreements, reserves, paid losses, recoverables, letters of credit, trust assets, haircuts, ratings, collateral calls, and releases.","Produce a governed agreement collateral terms decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Treaty / Trust Account","text","Treaty / Trust Account · Standard Case"],["caseReference","Agreement collateral terms Reference","text","RCT01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",768750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",930188],["domainDriver","Collateral Form","select","Trust",["Trust","Letter of credit","Funds withheld"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agreement collateral terms case","Reserve recoverable ingestion case","Paid loss recoverables case","Required collateral calculation case","Asset eligibility review case"]}),
feature("reserve-recoverable-ingestion","RCT02","Reserve recoverable ingestion","Execute reserve recoverable ingestion using reinsurance agreements, reserves, paid losses, recoverables, letters of credit, trust assets, haircuts, ratings, collateral calls, and releases.","Produce a governed reserve recoverable ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Treaty / Trust Account","text","Treaty / Trust Account · Standard Case"],["caseReference","Reserve recoverable ingestion Reference","text","RCT02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",768750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",930188],["domainDriver","Collateral Form","select","Trust",["Trust","Letter of credit","Funds withheld"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agreement collateral terms case","Reserve recoverable ingestion case","Paid loss recoverables case","Required collateral calculation case","Asset eligibility review case"]}),
feature("paid-loss-recoverables","RCT03","Paid loss recoverables","Execute paid loss recoverables using reinsurance agreements, reserves, paid losses, recoverables, letters of credit, trust assets, haircuts, ratings, collateral calls, and releases.","Produce a governed paid loss recoverables decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Treaty / Trust Account","text","Treaty / Trust Account · Standard Case"],["caseReference","Paid loss recoverables Reference","text","RCT03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",768750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",930188],["domainDriver","Collateral Form","select","Trust",["Trust","Letter of credit","Funds withheld"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agreement collateral terms case","Reserve recoverable ingestion case","Paid loss recoverables case","Required collateral calculation case","Asset eligibility review case"]}),
feature("required-collateral-calculation","RCT04","Required collateral calculation","Execute required collateral calculation using reinsurance agreements, reserves, paid losses, recoverables, letters of credit, trust assets, haircuts, ratings, collateral calls, and releases.","Produce a governed required collateral calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Treaty / Trust Account","text","Treaty / Trust Account · Standard Case"],["caseReference","Required collateral calculation Reference","text","RCT04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",768750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",930188],["domainDriver","Collateral Form","select","Trust",["Trust","Letter of credit","Funds withheld"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agreement collateral terms case","Reserve recoverable ingestion case","Paid loss recoverables case","Required collateral calculation case","Asset eligibility review case"]}),
feature("asset-eligibility-review","RCT05","Asset eligibility review","Execute asset eligibility review using reinsurance agreements, reserves, paid losses, recoverables, letters of credit, trust assets, haircuts, ratings, collateral calls, and releases.","Produce a governed asset eligibility review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Treaty / Trust Account","text","Treaty / Trust Account · Standard Case"],["caseReference","Asset eligibility review Reference","text","RCT05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",768750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",930188],["domainDriver","Collateral Form","select","Trust",["Trust","Letter of credit","Funds withheld"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agreement collateral terms case","Reserve recoverable ingestion case","Paid loss recoverables case","Required collateral calculation case","Asset eligibility review case"]}),
feature("valuation-haircut-calculation","RCT06","Valuation haircut calculation","Execute valuation haircut calculation using reinsurance agreements, reserves, paid losses, recoverables, letters of credit, trust assets, haircuts, ratings, collateral calls, and releases.","Produce a governed valuation haircut calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Treaty / Trust Account","text","Treaty / Trust Account · Standard Case"],["caseReference","Valuation haircut calculation Reference","text","RCT06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",768750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",930188],["domainDriver","Collateral Form","select","Trust",["Trust","Letter of credit","Funds withheld"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agreement collateral terms case","Reserve recoverable ingestion case","Paid loss recoverables case","Required collateral calculation case","Asset eligibility review case"]}),
feature("credit-rating-adjustment","RCT07","Credit rating adjustment","Execute credit rating adjustment using reinsurance agreements, reserves, paid losses, recoverables, letters of credit, trust assets, haircuts, ratings, collateral calls, and releases.","Produce a governed credit rating adjustment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Treaty / Trust Account","text","Treaty / Trust Account · Standard Case"],["caseReference","Credit rating adjustment Reference","text","RCT07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",768750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",930188],["domainDriver","Collateral Form","select","Trust",["Trust","Letter of credit","Funds withheld"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agreement collateral terms case","Reserve recoverable ingestion case","Paid loss recoverables case","Required collateral calculation case","Asset eligibility review case"]}),
feature("letter-of-credit-tracking","RCT08","Letter-of-credit tracking","Execute letter-of-credit tracking using reinsurance agreements, reserves, paid losses, recoverables, letters of credit, trust assets, haircuts, ratings, collateral calls, and releases.","Produce a governed letter-of-credit tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Treaty / Trust Account","text","Treaty / Trust Account · Standard Case"],["caseReference","Letter-of-credit tracking Reference","text","RCT08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",768750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",930188],["domainDriver","Collateral Form","select","Trust",["Trust","Letter of credit","Funds withheld"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agreement collateral terms case","Reserve recoverable ingestion case","Paid loss recoverables case","Required collateral calculation case","Asset eligibility review case"]}),
feature("trust-statement-reconciliation","RCT09","Trust statement reconciliation","Execute trust statement reconciliation using reinsurance agreements, reserves, paid losses, recoverables, letters of credit, trust assets, haircuts, ratings, collateral calls, and releases.","Produce a governed trust statement reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Treaty / Trust Account","text","Treaty / Trust Account · Standard Case"],["caseReference","Trust statement reconciliation Reference","text","RCT09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",768750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",930188],["domainDriver","Collateral Form","select","Trust",["Trust","Letter of credit","Funds withheld"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agreement collateral terms case","Reserve recoverable ingestion case","Paid loss recoverables case","Required collateral calculation case","Asset eligibility review case"]}),
feature("funds-withheld-balance","RCT10","Funds-withheld balance","Execute funds-withheld balance using reinsurance agreements, reserves, paid losses, recoverables, letters of credit, trust assets, haircuts, ratings, collateral calls, and releases.","Produce a governed funds-withheld balance decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Treaty / Trust Account","text","Treaty / Trust Account · Standard Case"],["caseReference","Funds-withheld balance Reference","text","RCT10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",768750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",930188],["domainDriver","Collateral Form","select","Trust",["Trust","Letter of credit","Funds withheld"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agreement collateral terms case","Reserve recoverable ingestion case","Paid loss recoverables case","Required collateral calculation case","Asset eligibility review case"]}),
feature("collateral-call-workflow","RCT11","Collateral call workflow","Execute collateral call workflow using reinsurance agreements, reserves, paid losses, recoverables, letters of credit, trust assets, haircuts, ratings, collateral calls, and releases.","Produce a governed collateral call workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Treaty / Trust Account","text","Treaty / Trust Account · Standard Case"],["caseReference","Collateral call workflow Reference","text","RCT11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",768750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",930188],["domainDriver","Collateral Form","select","Trust",["Trust","Letter of credit","Funds withheld"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agreement collateral terms case","Reserve recoverable ingestion case","Paid loss recoverables case","Required collateral calculation case","Asset eligibility review case"]}),
feature("excess-release-calculation","RCT12","Excess release calculation","Execute excess release calculation using reinsurance agreements, reserves, paid losses, recoverables, letters of credit, trust assets, haircuts, ratings, collateral calls, and releases.","Produce a governed excess release calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Treaty / Trust Account","text","Treaty / Trust Account · Standard Case"],["caseReference","Excess release calculation Reference","text","RCT12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",768750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",930188],["domainDriver","Collateral Form","select","Trust",["Trust","Letter of credit","Funds withheld"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agreement collateral terms case","Reserve recoverable ingestion case","Paid loss recoverables case","Required collateral calculation case","Asset eligibility review case"]}),
feature("counterparty-dispute-evidence","RCT13","Counterparty dispute evidence","Execute counterparty dispute evidence using reinsurance agreements, reserves, paid losses, recoverables, letters of credit, trust assets, haircuts, ratings, collateral calls, and releases.","Produce a governed counterparty dispute evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Treaty / Trust Account","text","Treaty / Trust Account · Standard Case"],["caseReference","Counterparty dispute evidence Reference","text","RCT13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",768750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",930188],["domainDriver","Collateral Form","select","Trust",["Trust","Letter of credit","Funds withheld"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agreement collateral terms case","Reserve recoverable ingestion case","Paid loss recoverables case","Required collateral calculation case","Asset eligibility review case"]}),
feature("accounting-reconciliation","RCT14","Accounting reconciliation","Execute accounting reconciliation using reinsurance agreements, reserves, paid losses, recoverables, letters of credit, trust assets, haircuts, ratings, collateral calls, and releases.","Produce a governed accounting reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Treaty / Trust Account","text","Treaty / Trust Account · Standard Case"],["caseReference","Accounting reconciliation Reference","text","RCT14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",768750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",930188],["domainDriver","Collateral Form","select","Trust",["Trust","Letter of credit","Funds withheld"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agreement collateral terms case","Reserve recoverable ingestion case","Paid loss recoverables case","Required collateral calculation case","Asset eligibility review case"]}),
feature("treaty-counterparty-analytics","RCT15","Treaty counterparty analytics","Execute treaty counterparty analytics using reinsurance agreements, reserves, paid losses, recoverables, letters of credit, trust assets, haircuts, ratings, collateral calls, and releases.","Produce a governed treaty counterparty analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Treaty / Trust Account","text","Treaty / Trust Account · Standard Case"],["caseReference","Treaty counterparty analytics Reference","text","RCT15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",768750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",930188],["domainDriver","Collateral Form","select","Trust",["Trust","Letter of credit","Funds withheld"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Agreement collateral terms case","Reserve recoverable ingestion case","Paid loss recoverables case","Required collateral calculation case","Asset eligibility review case"]})
]);
